server {
    listen 80;
    server_name localhost;

    # Корень — web-папка Yii2
    root /var/www/html/web;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Передача PHP-запросов в php-fpm
    location ~ \.php$ {
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }

    # Закрыть прямой доступ к .ht-файлам
    location ~ /\.ht {
        deny all;
    }
}